version: '3.1'

services:

  sut:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: /run_tests.sh
    depends_on:
      - proxy

  proxy:
    build:
      context: .
    container_name: proxy